#!/usr/bin/env python3
"""Generate wasm/bge-embed/src/unicode-data.c.

Reproduces the Unicode tables the WPM tokenizer needs, using the SAME public
algorithm as llama.cpp's scripts/gen-unicode-data.py so our C tokenizer matches
the llama.cpp WPM tokenizer codepoint-for-codepoint:

  * category flags  : from UnicodeData.txt field 2 (general category)
  * simple lowercase: from UnicodeData.txt field 13
  * NFD first cpt   : from Python's unicodedata.normalize('NFD', chr(cpt))[0]
  * whitespace set  : the explicit list from the Unicode <White_Space> property

This is a clean-room reimplementation (no upstream code copied) — only the
public, standard-defined mapping is reproduced.

Usage:
  python gen-unicode-data.py [UnicodeData.txt] > unicode-data.c

If the path is omitted it looks for a cached copy next to this script
(unicode-data.txt) and otherwise downloads it from unicode.org.
"""
from __future__ import annotations

import os
import sys
import unicodedata
import urllib.request

MAX_CODEPOINTS = 0x110000
UNICODE_DATA_URL = "https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt"

# Category -> flag bit. Must match BGE_UC_* in unicode-data.h.
FLAG_UNDEFINED = 0x0001
FLAG_NUMBER = 0x0002
FLAG_LETTER = 0x0004
FLAG_SEPARATOR = 0x0008
FLAG_MARK = 0x0010
FLAG_PUNCTUATION = 0x0020
FLAG_SYMBOL = 0x0040
FLAG_CONTROL = 0x0080

CATEGORY_TO_FLAG = {
    "Cn": FLAG_UNDEFINED, "Cc": FLAG_CONTROL, "Cf": FLAG_CONTROL,
    "Co": FLAG_CONTROL, "Cs": FLAG_CONTROL,
    "Ll": FLAG_LETTER, "Lm": FLAG_LETTER, "Lo": FLAG_LETTER,
    "Lt": FLAG_LETTER, "Lu": FLAG_LETTER, "L&": FLAG_LETTER,
    "Mc": FLAG_MARK, "Me": FLAG_MARK, "Mn": FLAG_MARK,
    "Nd": FLAG_NUMBER, "Nl": FLAG_NUMBER, "No": FLAG_NUMBER,
    "Pc": FLAG_PUNCTUATION, "Pd": FLAG_PUNCTUATION, "Pe": FLAG_PUNCTUATION,
    "Pf": FLAG_PUNCTUATION, "Pi": FLAG_PUNCTUATION, "Po": FLAG_PUNCTUATION,
    "Ps": FLAG_PUNCTUATION,
    "Sc": FLAG_SYMBOL, "Sk": FLAG_SYMBOL, "Sm": FLAG_SYMBOL, "So": FLAG_SYMBOL,
    "Zl": FLAG_SEPARATOR, "Zp": FLAG_SEPARATOR, "Zs": FLAG_SEPARATOR,
}


def load_unicode_data() -> str:
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as fh:
            return fh.read()
    cache = os.path.join(os.path.dirname(os.path.abspath(__file__)), "unicode-data.txt")
    if os.path.exists(cache):
        with open(cache, encoding="utf-8") as fh:
            return fh.read()
    sys.stderr.write(f"downloading {UNICODE_DATA_URL}\n")
    data = urllib.request.urlopen(UNICODE_DATA_URL).read().decode()
    with open(cache, "w", encoding="utf-8") as fh:
        fh.write(data)
    return data


def iter_rows(text: str):
    """Yield (cpt, lower, category), expanding First/Last range rows."""
    prev = None
    for line in text.splitlines():
        f = line.split(";")
        cpt = int(f[0], 16)
        lower = int(f[13] or "0", 16)
        categ = f[2].strip()
        name = f[1]
        if name.endswith(", First>"):
            prev = (cpt, lower, categ)
            continue
        if name.endswith(", Last>"):
            start, plower, pcateg = prev
            for c in range(start, cpt):
                yield (c, plower, pcateg)
            prev = None
        yield (cpt, lower, categ)


def main() -> None:
    text = load_unicode_data()

    flags = [FLAG_UNDEFINED] * MAX_CODEPOINTS
    lowercase: list[tuple[int, int]] = []
    nfd: list[tuple[int, int]] = []

    for cpt, lower, categ in iter_rows(text):
        flags[cpt] = CATEGORY_TO_FLAG[categ]
        if lower:
            lowercase.append((cpt, lower))
        norm = ord(unicodedata.normalize("NFD", chr(cpt))[0])
        if cpt != norm:
            nfd.append((cpt, norm))

    # Explicit whitespace set (Unicode <White_Space>), as in llama.cpp.
    whitespace = sorted(set(
        list(range(0x09, 0x0D + 1)) + list(range(0x2000, 0x200A + 1)) +
        [0x20, 0x85, 0xA0, 0x1680, 0x2028, 0x2029, 0x202F, 0x205F, 0x3000]
    ))

    # Run-length encode the flags array into (start, flags) ranges.
    ranges: list[tuple[int, int]] = [(0, flags[0])]
    for cpt in range(1, MAX_CODEPOINTS):
        if flags[cpt] != ranges[-1][1]:
            ranges.append((cpt, flags[cpt]))
    ranges.append((MAX_CODEPOINTS, 0x0000))  # sentinel

    lowercase.sort()
    nfd.sort()

    w = sys.stdout.write
    w("/* GENERATED by wasm/bge-embed/tools/gen-unicode-data.py — do not edit. */\n")
    w('#include "unicode-data.h"\n\n')

    w("const bge_uc_range_flags bge_uc_ranges_flags[] = {\n")
    for start, fl in ranges:
        w("  {0x%06X, 0x%04X},\n" % (start, fl))
    w("};\n")
    w("const int bge_uc_ranges_flags_count = %d;\n\n" % len(ranges))

    w("const uint32_t bge_uc_whitespace[] = {\n")
    for cpt in whitespace:
        w("  0x%06X,\n" % cpt)
    w("};\n")
    w("const int bge_uc_whitespace_count = %d;\n\n" % len(whitespace))

    w("const bge_uc_pair bge_uc_lowercase[] = {\n")
    for k, v in lowercase:
        w("  {0x%06X, 0x%06X},\n" % (k, v))
    w("};\n")
    w("const int bge_uc_lowercase_count = %d;\n\n" % len(lowercase))

    w("const bge_uc_pair bge_uc_nfd[] = {\n")
    for k, v in nfd:
        w("  {0x%06X, 0x%06X},\n" % (k, v))
    w("};\n")
    w("const int bge_uc_nfd_count = %d;\n" % len(nfd))


if __name__ == "__main__":
    main()
